baseURL = "https://blog.lukas-ross.de/"
languageCode = "de-DE"
locale = "de"
title = "Lukas' Tech Blog"
theme = "papermod"

[params]
  env = "production"
  title = "Lukas' Tech Blog"
  description = "Mein persönlicher Blog"
  author = "Lukas"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true