backend:
  name: github
  repo: Addereum/lukasrossblog # Hier dein GitHub Repo einragen
  branch: main
  base_url: https://celadon-sable-4727e8.netlify.app # Hier MUSS die echte Netlify-App-URL stehen für den Auth-Proxy!
  site_url: https://blog.lukas-ross.de
  auth_type: implicit

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
